# Generated by Django 2.2.27 on 2023-05-17 10:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='In which category you want to seperate your project layer', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description about this category', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('project', models.ForeignKey(help_text='Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'MeasuringCategory',
                'verbose_name_plural': 'MeasuringCategories',
            },
        ),
        migrations.CreateModel(
            name='CategoryGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('measuring_category', models.ForeignKey(help_text='Geometry related to this Category', on_delete=django.db.models.deletion.PROTECT, to='app.MeasuringCategory', verbose_name='Measuring Category')),
            ],
            options={
                'verbose_name': 'CategoryGeometry',
                'verbose_name_plural': 'CategoryGeometries',
            },
        ),
    ]
