# Generated by Django 2.2.27 on 2023-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_categorygeometry_measuringcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='A label used to describe the project', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
