# Generated by Django 2.2.27 on 2023-05-28 07:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20230527_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygeometry',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=3857),
        ),
    ]
