# Generated by Django 2.2.27 on 2023-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20230528_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringcategory',
            name='publised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measuringcategory',
            name='view_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
