# Generated by Django 2.2.27 on 2023-05-31 11:52

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20230531_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('fill', colorfield.fields.ColorField(default='#2c3e50', help_text='Fill color for the polygon', max_length=18, verbose_name='Fill Color')),
                ('fill_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('stroke', colorfield.fields.ColorField(default='#ffffff', help_text='Stroke coloe for the polygon', max_length=18, verbose_name='Stroke Color')),
                ('stroke_width', models.PositiveIntegerField(default=1)),
                ('xml', models.TextField(blank=True, null=True)),
                ('measuring_category', models.ForeignKey(help_text='Geometry related to this Category', on_delete=django.db.models.deletion.PROTECT, to='app.MeasuringCategory', verbose_name='Measuring Category')),
            ],
            options={
                'verbose_name': 'CategoryStyle',
                'verbose_name_plural': 'CategoryStyles',
            },
        ),
    ]
