# Generated by Django 2.2.27 on 2023-06-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringcategory',
            name='standard_category',
            field=models.ForeignKey(blank=True, help_text='Standard Category related to the project', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.StandardCategory', verbose_name='Standard Category'),
        ),
        migrations.AddField(
            model_name='measuringcategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Sub Category related to the project', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.SubCategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='measuringcategory',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Category related to the project', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Project', verbose_name='Project'),
        ),
    ]
