# Generated by Django 2.2.27 on 2023-06-12 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_categorystyle_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStandardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='In which standard category you want to seperate your project layer', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description about this category', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='In which Sub category you want to seperate your project layer', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description about this category', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('standard_category', models.ForeignKey(blank=True, help_text='Standard Category related to the project', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.GlobalStandardCategory', verbose_name='Standard Category')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMeasuringCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='In which category you want to seperate your project layer', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description about this category', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('sub_category', models.ForeignKey(blank=True, help_text='Sub Category related to the project', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.GlobalSubCategory', verbose_name='Sub Category')),
            ],
        ),
    ]
