# Generated by Django 2.2.27 on 2023-06-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_globalmeasuringcategory_globalstandardcategory_globalsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalstandardcategory',
            name='name',
            field=models.CharField(help_text='In which standard category you want to seperate your project layer', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ManageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(blank=True, null=True, to='app.GlobalMeasuringCategory')),
                ('project', models.OneToOneField(help_text='Standard Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.Project', verbose_name='Project')),
                ('standard_category', models.ManyToManyField(blank=True, null=True, to='app.GlobalStandardCategory')),
                ('sub_category', models.ManyToManyField(blank=True, null=True, to='app.GlobalSubCategory')),
            ],
        ),
    ]
