# Generated by Django 2.2.27 on 2023-06-13 04:23

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20230612_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managecategory',
            name='project',
            field=models.OneToOneField(help_text='Manage Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.Project', verbose_name='Project'),
        ),
        migrations.CreateModel(
            name='GlobalCategoryStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill', colorfield.fields.ColorField(default='#2c3e50', help_text='Fill color for the polygon', max_length=18, verbose_name='Fill Color')),
                ('fill_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('stroke', colorfield.fields.ColorField(default='#ffffff', help_text='Stroke color for the polygon', max_length=18, verbose_name='Stroke Color')),
                ('stroke_width', models.PositiveIntegerField(default=1)),
                ('xml', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('category', models.OneToOneField(help_text='Style related to this Category', on_delete=django.db.models.deletion.PROTECT, to='app.GlobalMeasuringCategory', verbose_name='Category')),
            ],
        ),
    ]
