# Generated by Django 2.2.27 on 2023-06-13 05:38

import app.models.measuring_category
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20230613_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalstandardcategory',
            name='name',
            field=app.models.measuring_category.CaseInsensitiveCharField(help_text='Standard Category name', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
