# Generated by Django 2.2.27 on 2023-06-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20230613_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsubcategory',
            name='standard_category',
            field=models.ForeignKey(help_text='Standard Category related to the project', on_delete=django.db.models.deletion.PROTECT, to='app.GlobalStandardCategory', verbose_name='Standard Category'),
        ),
    ]
