# Generated by Django 2.2.27 on 2023-06-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20230613_0541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalsubcategory',
            unique_together={('standard_category', 'name')},
        ),
    ]
