# Generated by Django 2.2.27 on 2023-06-29 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20230613_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygeometry',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
